#docker-compose version
version: '3.1'
services:
  jrtb:
    build:
      context: .
    environment:
      BOT_NAME: test_JavaAcorn_bot
      BOT_TOKEN: 5578041606:AAHHXNOU4w82W1QhOR7lqfjUVTnqSpV6qvU
    restart: always