version: '3.1'

services:
  jrtb-bot:
    depends_on: ##сначала запускается jrtb-db. База данных
      - jrtb-db
    build:
      context: .
    environment:
      BOT_NAME: test_JavaAcorn_bot
      BOT_TOKEN: 5578041606:AAFOrM62Te-r0xx2jIzhRXZJrREXyEP6YCE
      BOT_DB_USERNAME: botusername
      BOT_DB_PASSWORD: botpassword
    restart: always
  jrtb-db:
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_USER: botusername
      MYSQL_PASSWORD: botpassword
      MYSQL_DATABASE: jrtb_db
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3308:3306'
    expose:
      - '3308'
    command: --character-set-server=utf8 --collation-server=utf8_general_ci